{% set name = "data2objects" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/data2objects-{{ version }}.tar.gz
  sha256: 9c0bb1d918c83e107aac897f00df69033d173c968972d68b776c280b04aea18c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - data2objects
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jla-gardner/data2objects
  summary: Transform nested data structures into Python objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
